/*
 * build.gradle
 *
 * Copyright by toolarium, all rights reserved.
 */
apply from: "https://raw.githubusercontent.com/toolarium/common-gradle-build/master/gradle/common.gradle"


/***************************************************************************************
 * define the main class name
 ***************************************************************************************/
jar {
    manifest {
        attributes 'Main-Class': 'com.github.toolarium.dependency.check.main.DependencyCheckMain'
    }
}


/****************************************************************************************
 * Define project dependencies
 ****************************************************************************************/
dependencies {
    implementation "com.github.toolarium:toolarium-common:1.0.0"
    implementation "com.github.toolarium:toolarium-ansi:0.9.0"

    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations
    implementation "com.fasterxml.jackson.core:jackson-databind:2.21.3"
    implementation "com.fasterxml.jackson.core:jackson-core:2.21.3"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.21.3"

    // logging
    implementation "org.slf4j:slf4j-api:${commonGradleSlf4jApiVersion}"
    testRuntimeOnly "ch.qos.logback:logback-classic:${commonGradleLogbackVersion}"
}
